name             'kubernetes'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kubernetes'
long_description 'Installs/Configures kubernetes'
version          '0.1.0'
depends          'dbag'
